### ISSUE TITLE
Is injectScript needed for this template?

### ISSUE THREAD

**Issue by philpott** [sassoftware/sas-ci360-template-google-tag-manager#1]
https://github.com/sassoftware/sas-ci360-template-google-tag-manager/blob/dc3287315dcdf089c8ec71836bb21555cacb7dbc/template.tpl#L289

I see that inject script is being required into the template but I'm not seeing it used. If the template isn't going to load the tag itself you might want to remove this to reduce the permissions that your template says it requires.

**Comment by jeff-stroud-sas** [comment]
You're correct, was part of testing earlier. It's been removed from the template and metadata file has been updated!
